"""Markdown report builders for PR comments and Slack Block Kit messages."""
from typing import Any, Dict, Optional, List


_VERDICT_EMOJI = {
    "pass": "white_check_mark",
    "warn": "warning",
    "block": "rotating_light",
}


_VERDICT_COLOR = {
    "pass": "#22c55e",  # Emerald
    "warn": "#f59e0b",  # Amber
    "block": "#ef4444",  # Rose
}


def _emoji(verdict: str) -> str:
    return f":{_VERDICT_EMOJI.get(verdict, 'grey_question')}:"


def _severity_label(score: int) -> str:
    if score >= 75:
        return "CRITICAL"
    if score >= 50:
        return "HIGH"
    if score >= 25:
        return "MEDIUM"
    return "LOW"


def build_pr_comment(
    plan: Dict[str, Any],
    policy_result: Optional[Dict[str, Any]],
    verdict: str,
    auto_fix: Optional[Dict[str, Any]] = None,
) -> str:
    ranked = plan.get("ranked_choice", {})
    severity = ranked.get("predicted_severity", 0)
    blast_radius = ranked.get("predicted_blast_radius", 0)
    benefit = ranked.get("predicted_benefit", 0)
    effort = ranked.get("predicted_effort", 0)
    confidence = ranked.get("confidence", 0.0)
    scenario = ranked.get("scenario_type", "unknown")
    evidence = ranked.get("evidence", [])
    dashboards = ranked.get("affected_dashboards", 0)
    models = ranked.get("affected_models", 0)
    pipelines = ranked.get("affected_pipelines", 0)
    asset_urn = plan.get("asset_urn", "")

    lines: List[str] = []
    lines.append(f"## {_emoji(verdict)} Cortex Autopilot Impact Report")
    lines.append("")
    lines.append(f"<table>")
    lines.append("<tr>")
    lines.append(f"<th align='left'>Verdict</th><td><code>{verdict.upper()</code</td>")
    lines.append("</tr>")
    lines.append("<tr>")
    lines.append(f"<th align='left'>Asset</th><td><code>{asset_urn</code</td>")
    lines.append("</tr>")
    lines.append("<tr>")
    lines.append(
        f"<th align='left'>Severity</th>"
        f"<td><strong>{_severity_label(severity)}</strong> ({severity}/100</td>"
    )
    lines.append("</tr>")
    lines.append("<tr>")
    lines.append(
        f"<th align='left'>Blast Radius</th><td>{blast_radius} downstream assets</td>"
    )
    lines.append("</tr>")
    if dashboards or models or pipelines:
        lines.append("<tr>")
        details = []
        if dashboards:
            details.append(f"{dashboards} dashboards")
        if models:
            details.append(f"{models} ML models")
        if pipelines:
            details.append(f"{pipelines} pipelines")
        lines.append(f"<th align='left'>Affected</th><td>{', '.join(details)}</td>")
        lines.append("</tr>")
    lines.append("</table>")
    lines.append("")

    lines.append("### Recommended action")
    lines.append("")
    lines.append(f"- **Action:** `{scenario}`")
    lines.append(f"- **Predicted benefit:** {benefit}/100")
    lines.append(f"- **Predicted effort:** {effort}/100")
    lines.append(f"- **Confidence:** {confidence:.0%}")
    lines.append("")

    explanation = plan.get("explanation", [])
    if explanation:
        lines.append("### Why this verdict")
        lines.append("")
        for line in explanation[:6]:
            lines.append(f"- {line}")
        lines.append("")

    if evidence:
        lines.append("### Evidence")
        lines.append("")
        for ev in evidence[:5]:
            lines.append(f"- {ev}")
        lines.append("")

    if policy_result and policy_result.get("results"):
        lines.append("### Policy evaluation")
        lines.append("")
        lines.append("| Policy | Verdict | Reason |")
        lines.append("|---|---|---|")
        for r in policy_result["results"]:
            lines.append(
                f"| {r.get('policy_name', '-')} "
                f"| `{r.get('verdict', '-').upper()}` "
                f"| {r.get('reason', '-')} |"
            )
        lines.append("")

    if auto_fix and auto_fix.get("body"):
        lines.append("### :sparkles: Suggested auto-fix")
        lines.append("")
        artifact_type = auto_fix.get("artifact_type", "sql")
        title = auto_fix.get("title", "Suggested fix")
        confidence = auto_fix.get("confidence", 0.0)
        lines.append(
            "Cortex generated a ready-to-apply migration to address this "
            "verdict. Review carefully before applying — auto-generated "
            "scripts need human sign-off."
        )
        lines.append("")
        lines.append("<details>")
        lines.append(
            f"<summary><strong>{title}</strong> "
            f"(`{artifact_type}`, confidence {confidence:.0%})</summary>"
        )
        lines.append("")
        lines.append("```" + artifact_type)
        lines.append(auto_fix["body"].rstrip())
        lines.append("```")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by [Cortex Autopilot Impact Gate](https://cortex.dev)._")

    return "\n".join(lines)


def build_slack_message(
    plan: Dict[str, Any],
    policy_result: Optional[Dict[str, Any]],
    verdict: str,
    pr_number: Optional[int],
) -> Dict[str, Any]:
    """Build a Slack Block Kit payload for the verdict.

    Uses Slack's interactive Block Kit so the alert has a polished layout:
    a header block, a colored context bar (using emoji + section blocks),
    a key/value fields block, and an action block with "View PR" /
    "View Impact Report" buttons.
    """
    import os

    ranked = plan.get("ranked_choice", {})
    severity = ranked.get("predicted_severity", 0)
    blast_radius = ranked.get("predicted_blast_radius", 0)
    scenario = ranked.get("scenario_type", "unknown")
    asset_urn = plan.get("asset_urn", "")

    repo = os.environ.get("GITHUB_REPOSITORY", "")
    color = _VERDICT_COLOR.get(verdict, "#94a3b8")
    severity_label = _severity_label(severity)

    pr_link_text = ""
    pr_url = None
    if pr_number is not None and repo:
        pr_url = f"https://github.com/{repo}/pull/{pr_number}"
        pr_link_text = f"PR #{pr_number} in `{repo}`"

    text = (
        f"{_emoji(verdict)} *Cortex Autopilot {verdict.upper()}*\n"
        f"Asset: `{asset_urn}`\n"
        f"Severity: {severity_label} ({severity}/100)\n"
        f"Blast radius: {blast_radius} downstream assets\n"
        f"Recommended action: `{scenario}`"
    )

    blocks: List[Dict[str, Any]] = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"{_emoji(verdict)} Cortex Autopilot {verdict.upper()}",
                "emoji": True,
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Asset*\n`{asset_urn}`"},
                {"type": "mrkdwn", "text": f"*Severity*\n{severity_label} ({severity}/100)"},
                {"type": "mrkdwn", "text": f"*Blast Radius*\n{blast_radius} downstream"},
                {"type": "mrkdwn", "text": f"*Recommended Action*\n`{scenario}`"},
            ],
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": (
                        f":large_blue_circle: <!subteam^data-platform> "
                        f"color: `{color}`  •  Generated by Cortex Autopilot"
                    ),
                }
            ],
        },
    ]

    # Add an interactive action block when we have a PR link.
    if pr_url:
        blocks.append(
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "View PR"},
                        "url": pr_url,
                        "style": "primary" if verdict == "block" else "default",
                    },
                ],
            }
        )

    if policy_result and policy_result.get("results"):
        policy_text = "\n".join(
            f"• `{r.get('policy_name', '?')}`: "
            f"*{r.get('verdict', '?').upper()}* — {r.get('reason', '')}"
            for r in policy_result["results"][:4]
        )
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*Policies triggered*\n{policy_text}"},
            }
        )

    return {"text": text, "blocks": blocks, "color": color}
