"""workflo explain — why did Workflo report this finding? (7B.6).

Explain answers "Why did Workflo report this finding?" using ONLY the
explanation material recorded in the receipt at run time:

  * finding summaries and recorded agent assessments (agent_reasoning)
  * the run outcome (status, failure stage, collection error)
  * evidence refs, resolved against the evidence ledger

It NEVER invokes the model again — there is no fresh interpretation,
no re-analysis, no hosted inference. The label for recorded model text
is "Recorded agent assessment" (never a raw "thinking log"), and the
output always carries explanation provenance metadata (7B.7):

    Explanation source: recorded_agent_assessment
    Generated by: workflo-cli

AGENT INTERPRETATION is not RUNTIME PROOF: the assessment explains the
finding, the evidence chain proves it. A future --ai mode (new model
interpretation) is explicitly deferred and must never be mixed with
this recorded output.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

import click

from workflo_cli.artifacts import (
    EVIDENCE_INVALID,
    EVIDENCE_MISSING,
    EVIDENCE_NONE,
    EvidenceBundleView,
    FindingView,
    STATUS_VERIFIED,
    TrustContext,
    build_trust_context,
    select_findings,
    wrap,
)
from workflo_cli.exit_codes import (
    EXIT_CONFIGURATION_ERROR,
    EXIT_VERIFIED,
    EXIT_VERIFICATION_FAILED,
)

# Explanation provenance sources (7B.7) — recorded material only
SOURCE_AGENT_ASSESSMENT = "recorded_agent_assessment"
SOURCE_FINDING = "recorded_finding"
SOURCE_RUN_OUTCOME = "recorded_run_outcome"


def get_version() -> str:
    """The CLI version, imported lazily.

    Importing `workflo_cli.__version__` at module level would be circular:
    workflo_cli/__init__.py imports main.py, which imports this module.
    """
    from workflo_cli import __version__

    return __version__ or "0.0.0"


def _explanation_source(findings: list[FindingView]) -> str:
    if not findings:
        return SOURCE_RUN_OUTCOME
    if any(f.agent_reasoning for f in findings):
        return SOURCE_AGENT_ASSESSMENT
    return SOURCE_FINDING


def _ref_line(ref: str, view: EvidenceBundleView) -> str:
    """One evidence ref with its trust status — never fabricated."""
    if view.status == EVIDENCE_INVALID:
        return f"{ref} (UNTRUSTED — evidence chain failed verification)"
    if view.status in (EVIDENCE_MISSING, EVIDENCE_NONE):
        return (
            f"{ref} (NOT AVAILABLE — evidence bundle not found; recorded "
            "in the receipt, never fabricated)"
        )
    if ref in view.events:
        ev = view.events[ref]
        return f"{ref} (observed: {ev.event_type} @ {ev.timestamp})"
    return f"{ref} (NOT FOUND in ledger; never fabricated)"


def _finding_block(f: FindingView, view: EvidenceBundleView) -> list[str]:
    lines = [f"  {f.display_id} [{f.severity.upper()}] {f.title} — {f.status}"]
    if f.summary:
        lines.extend(wrap(f"Summary: {f.summary}", indent="    "))
    if f.agent_reasoning:
        lines.append("    Recorded agent assessment:")
        lines.extend(wrap(f.agent_reasoning, indent="      "))
    if f.evidence_refs:
        for ref in f.evidence_refs:
            lines.append(f"    Evidence: {_ref_line(ref, view)}")
    else:
        lines.append("    Evidence: (none recorded)")
    if f.reproduction:
        lines.append("    Reproduction:")
        for k, v in f.reproduction.items():
            lines.extend(wrap(f"{k}: {v}", indent="      "))
    return lines


def _run_outcome_block(trust: TrustContext) -> list[str]:
    r = trust.receipt
    rr = r.run_report
    lines = []
    if r.run_status == "failed":
        stage = f" at stage '{r.failure_stage}'" if r.failure_stage else ""
        lines.append(
            f"  The execution failed{stage}. No findings were recorded, "
            "so there is no finding to explain."
        )
        if rr.collection_error:
            lines.extend(
                wrap(f"The recorded collection error is: {rr.collection_error}",
                     indent="  ")
            )
        lines.append(
            "  This is an honest receipt for a failed run — execution "
            "failure is not receipt invalidity."
        )
    else:
        skipped = f", {rr.skipped} skipped" if rr.skipped else ""
        lines.append(
            f"  This run completed successfully with no findings recorded: "
            f"{rr.passed}/{rr.total} tests passed{skipped}. There is no "
            "finding to explain."
        )
    return lines


def render_explain(
    trust: TrustContext,
    receipt_label: str,
    selected: Optional[list[FindingView]],
) -> str:
    findings = selected if selected is not None else trust.findings
    source = _explanation_source(findings)
    if selected is not None:
        question = f"Why did Workflo report finding {selected[0].display_id}?"
    else:
        question = "Why did Workflo report these findings?"

    lines = [f"Workflo Explain — {receipt_label}", ""]
    lines.append("QUESTION")
    lines.append(f"  {question}")
    lines.append("")

    if selected is not None:
        lines.append("FINDING")
        lines.extend(_finding_block(selected[0], trust.evidence))
        lines.append("")
    elif findings:
        lines.append(f"FINDINGS ({len(findings)})")
        for f in findings:
            lines.append("")
            lines.extend(_finding_block(f, trust.evidence))
        lines.append("")
    else:
        lines.append("RUN OUTCOME")
        lines.extend(_run_outcome_block(trust))
        lines.append("")

    lines.append("EXPLANATION PROVENANCE")
    lines.append(f"  Explanation source: {source}")
    lines.append(f"  Generated by: workflo-cli {get_version()}")
    lines.append(
        "  This explanation is recorded material from the run receipt. "
        "No model was invoked to produce it."
    )
    lines.append(
        "  AGENT INTERPRETATION is not RUNTIME PROOF: the assessment "
        "explains the finding, the evidence chain proves it."
    )
    return "\n".join(lines)


def run_explain(
    receipt_path: str,
    finding_spec: Optional[str] = None,
    pubkey: Optional[str] = None,
    evidence_dir: Optional[str] = None,
) -> tuple[str, int]:
    """Run the explain analysis. Returns (output, exit_code)."""
    path = Path(receipt_path)
    if not path.exists():
        return (
            f"ERROR: receipt file not found: {receipt_path}",
            EXIT_CONFIGURATION_ERROR,
        )

    trust = build_trust_context(
        path,
        pubkey_path=Path(pubkey) if pubkey else None,
        evidence_override=Path(evidence_dir) if evidence_dir else None,
    )

    status = trust.status
    if status != STATUS_VERIFIED:
        reasons = {
            "untrusted": (
                "its signature or evidence chain failed verification — "
                "the recorded material is not proven authentic"
            ),
            "corrupt": (
                "it could not be parsed — there is no recorded material "
                "to explain"
            ),
            "unsupported": (
                "it uses a protocol version this CLI does not support"
            ),
            "unverified": (
                "its signature could not be verified — no public key was "
                "available (pass --pubkey, or explain on the machine that "
                "ran the sandbox)"
            ),
        }
        reason = reasons.get(status, "it is not a verified artifact")
        return (
            f"WARNING: cannot explain this receipt (Status: {status.upper()}) "
            f"— {reason}.\n"
            "Explanation requires a VERIFIED receipt: recorded material is "
            "only shown when the artifact that recorded it is proven "
            "authentic.",
            EXIT_VERIFICATION_FAILED,
        )

    selected: Optional[list[FindingView]] = None
    if finding_spec is not None:
        selected = select_findings(trust.findings, finding_spec)
        if not selected:
            available = ", ".join(f.display_id for f in trust.findings) or "(none)"
            return (
                f"ERROR: no finding matches '{finding_spec}' "
                f"(available: {available})",
                EXIT_CONFIGURATION_ERROR,
            )

    return (render_explain(trust, receipt_path, selected), EXIT_VERIFIED)


@click.command("explain")
@click.argument("receipt", metavar="RECEIPT")
@click.option("--finding", "finding_spec", default=None,
              help="Explain one finding: display ID (F-001), finding_id, "
                   "or finding_id suffix")
@click.option("--pubkey", default=None,
              help="Path to an Ed25519 public key PEM used to verify the "
                   "receipt signature offline (no network fetch is performed)")
@click.option("--evidence", "evidence_dir", default=None,
              help="Path to the evidence bundle directory (default: "
                   "auto-resolve from the receipt)")
def explain_command(receipt, finding_spec, pubkey, evidence_dir):
    """Explain why Workflo reported this finding.

    Uses ONLY the explanation material recorded in the receipt (finding
    summaries, recorded agent assessments, run outcome) — it never
    invokes the model again, and none of this text is a thinking log.
    The output always carries explanation provenance metadata.

    \b
    Exit codes:
      0  explanation produced from recorded material
      4  receipt not verified (untrusted / unverified / corrupt / unsupported)
      5  configuration error (file not found, unknown --finding)
    """
    output, code = run_explain(
        receipt,
        finding_spec=finding_spec,
        pubkey=pubkey,
        evidence_dir=evidence_dir,
    )
    click.echo(output)
    sys.exit(code)
