-- AUTO-FIX EXAMPLE
-- Scenario: Patch Sql for orders
-- Type: sql
-- Confidence: 78%
-- Generated by: Cortex Autopilot Impact Gate
--
-- This file is a sample output for the cherry-on-top feature
-- described in HACKATHON.md. It demonstrates what Cortex would
-- post in the GitHub PR comment when a PR is blocked.

# Patch Sql Template
# Scenario: type_change

## Action
Implement patch_sql to address type_change.

## Notes
No specific template available - implement based on context.
