-- AUTO-FIX EXAMPLE
-- Scenario: Patch Sql for customer_ltv
-- Type: sql
-- Confidence: 85%
-- Generated by: Cortex Autopilot Impact Gate
--
-- This file is a sample output for the cherry-on-top feature
-- described in HACKATHON.md. It demonstrates what Cortex would
-- post in the GitHub PR comment when a PR is blocked.

-- SQL patch for column rename
-- Review downstream dependencies before applying.

ALTER TABLE customer_ltv RENAME COLUMN clv_score TO lifetime_value;

-- Update downstream views
-- CREATE OR REPLACE VIEW downstream_view AS
-- SELECT ..., lifetime_value AS clv_score, ... FROM customer_ltv;
