-- AUTO-FIX EXAMPLE
-- Scenario: Patch Sql for orders
-- Type: sql
-- Confidence: 85%
-- Generated by: Cortex Autopilot Impact Gate
--
-- This file is a sample output for the cherry-on-top feature
-- described in HACKATHON.md. It demonstrates what Cortex would
-- post in the GitHub PR comment when a PR is blocked.

-- SQL patch for column removal
-- WARNING: This will break downstream consumers.

-- Option 1: Create compatibility view
CREATE OR REPLACE VIEW orders_compat AS
SELECT 
    *,
    NULL AS customer_name  -- Placeholder for removed column
FROM orders;

-- Option 2: Update downstream queries to not reference customer_name
