"""Generate example auto-fix artifacts for the sample dbt project.

Demonstrates Cherry #1 — Auto-Fix PR Generation. The script runs
the existing `artifact_generator` against realistic scenarios:

  - Drop column from `orders` (breaks dashboard_feed)
  - Rename column in `stg_customers` (breaks customer_ltv)
  - Change type of `customer_ltv.clv_score`

For each scenario, the generated migration SQL is written to
`examples/sample_artifacts/` so judges can see what the auto-fix
output looks like without running the engine.

Usage:
    python examples/sample_artifacts/generate_examples.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
BACKEND_ROOT = REPO_ROOT / "backend"
sys.path.insert(0, str(BACKEND_ROOT))

from app.models.recommendation import Recommendation
from app.services.artifact_generator import generate_artifact


def _save(artifact, output_path: Path) -> None:
    """Write the artifact as a comment-prefixed SQL file."""
    header = (
        f"-- AUTO-FIX EXAMPLE\n"
        f"-- Scenario: {artifact.title}\n"
        f"-- Type: {artifact.artifact_type}\n"
        f"-- Confidence: {artifact.confidence:.0%}\n"
        f"-- Generated by: Cortex Autopilot Impact Gate\n"
        f"--\n"
        f"-- This file is a sample output for the cherry-on-top feature\n"
        f"-- described in HACKATHON.md. It demonstrates what Cortex would\n"
        f"-- post in the GitHub PR comment when a PR is blocked.\n\n"
    )
    output_path.write_text(header + artifact.body)


def scenario_drop_column() -> None:
    """Block: developer drops `customer_name` from `orders`.

    Blast radius: 1 downstream (dashboard_feed) tagged `critical` and
    `dashboard`. ML lineage is preserved because the column being
    dropped is not an ML feature.
    """
    rec = Recommendation(
        impact_id="demo-drop-column",
        action_type="patch_sql",
        title="Compatibility view for dropped column",
        rationale="Schema change drops customer_name from orders; downstream dashboard_feed breaks.",
        confidence=0.85,
        risk="low",
        artifacts=[],
    )
    artifact = generate_artifact(
        recommendation=rec,
        scenario_type="schema_remove",
        asset_name="orders",
        removed_column="customer_name",
    )
    _save(artifact, REPO_ROOT / "examples/sample_artifacts/auto_fix_column_remove.sql")


def scenario_rename_column() -> None:
    """Block: developer renames `clv_score` → `lifetime_value` in customer_ltv.

    Blast radius: 1 downstream (dashboard_feed) tagged `critical` and
    `dashboard`. ML feature pipeline reads `clv_score` — silent rename
    would emit NULL embeddings.
    """
    rec = Recommendation(
        impact_id="demo-rename-column",
        action_type="patch_sql",
        title="Backwards-compatible column rename",
        rationale="Schema change renames clv_score in customer_ltv; downstream dashboard_feed and ML feature pipeline break.",
        confidence=0.85,
        risk="low",
        artifacts=[],
    )
    artifact = generate_artifact(
        recommendation=rec,
        scenario_type="schema_rename",
        asset_name="customer_ltv",
        old_name="clv_score",
        new_name="lifetime_value",
    )
    _save(artifact, REPO_ROOT / "examples/sample_artifacts/auto_fix_column_rename.sql")


def scenario_type_change() -> None:
    """Block: developer changes type of `amount` in `orders` from INTEGER to VARCHAR.

    Coercion would silently corrupt downstream financial reports.
    """
    rec = Recommendation(
        impact_id="demo-type-change",
        action_type="patch_sql",
        title="Safe type change with explicit cast",
        rationale="Schema change alters column type in orders; downstream aggregates break.",
        confidence=0.78,
        risk="medium",
        artifacts=[],
    )
    artifact = generate_artifact(
        recommendation=rec,
        scenario_type="type_change",
        asset_name="orders",
    )
    _save(artifact, REPO_ROOT / "examples/sample_artifacts/auto_fix_type_change.sql")


if __name__ == "__main__":
    scenario_drop_column()
    scenario_rename_column()
    scenario_type_change()
    print("[ok] Wrote 3 example auto-fix artifacts to examples/sample_artifacts/")
