"""Metadata-aware test generator.

Reads DataHub schemas + lineage and emits pytest test modules that:
  - Validate schema columns against the source-of-truth from DataHub
  - Check nullability constraints (NOT NULL columns)
  - Check primary key uniqueness
  - Validate lineage continuity (upstream columns map to downstream)
  - Tag each test with SOC 2 controls for compliance reporting

The generated tests import from workflo_schema (same package family)
and use plain pytest fixtures so they drop into any CI/CD pipeline.
"""

from textwrap import dedent
from typing import Iterable
from datetime import datetime, timezone

from workflo_datahub.client import DataHubClient
from workflo_datahub.inspector import MetadataInspector
from workflo_datahub.models import DatasetSchema, ColumnInfo, LineageEdge, TestArtifact
from workflo_utils.logging import get_logger

logger = get_logger(__name__)


class TestGenerator:
    """Generates metadata-aware pytest test files from DataHub metadata."""

    def __init__(self, client: DataHubClient):
        self.client = client
        self.inspector = MetadataInspector(client)

    # ------------------------------------------------------------------ schema tests

    def generate_schema_tests(self, dataset_urn: str) -> TestArtifact:
        """Generate a pytest module validating the dataset schema."""
        schema = self.inspector.get_dataset_schema(dataset_urn)
        return TestArtifact(
            test_name=f"test_schema_{self._slug(schema.name)}",
            test_code=self._render_schema_test(schema),
            dataset_urn=dataset_urn,
            description=f"Schema integrity test for {schema.name} ({schema.platform}). Auto-generated from DataHub.",
            soc2_controls=["CC6.1", "CC7.2"],
        )

    def _render_schema_test(self, schema: DatasetSchema) -> str:
        expected_columns = [(c.name, c.type, c.nullable) for c in schema.columns]
        expected_repr = repr(sorted([(n, t, "NULL" if nu else "NOT NULL") for n, t, nu in expected_columns]))
        pk_cols = self.inspector.primary_key_columns(schema)
        score = self.inspector.schema_integrity_score(schema)
        owner_line = schema.owner or "unknown"

        null_names = [c.name for c in schema.columns if c.nullable]
        nonnull_names = [c.name for c in schema.columns if not c.nullable]

        code = dedent(f'''\
            """Schema integrity test for {schema.name} on {schema.platform}.

            Auto-generated by Tenant Shield from DataHub metadata at {datetime.now(timezone.utc).isoformat()}.
            Owner: {owner_line}
            Schema integrity score: {score}

            SOC 2 controls: CC6.1 (data integrity), CC7.2 (system monitoring).
            """
            import pytest

            from tests.helpers.schema_validator import validate_schema, validate_nullable, validate_primary_key


            DATASET_URN = "{schema.urn}"
            EXPECTED_COLUMNS = {expected_repr}
            PRIMARY_KEY_COLUMNS = {pk_cols!r}
            _NULLABLE_COLUMNS = {null_names!r}
            _NON_NULLABLE_COLUMNS = {nonnull_names!r}


            @pytest.mark.security
            @pytest.mark.schema
            class Test{self._pascal(schema.name)}Schema:
                """Validate the {schema.name} schema against DataHub source-of-truth."""

                def test_expected_columns_present(self, db_connection):
                    """Ensure every expected column appears in the live table."""
                    missing = validate_schema(db_connection, "{schema.name}", EXPECTED_COLUMNS)
                    assert not missing, f"Missing columns: {{missing}}"

                def test_primary_key_unique(self, db_connection):
                    """Primary key columns MUST be unique and non-null."""
                    if not PRIMARY_KEY_COLUMNS:
                        pytest.skip("No primary key declared in DataHub")
                    dupes = validate_primary_key(db_connection, "{schema.name}", PRIMARY_KEY_COLUMNS)
                    assert not dupes, f"Duplicate primary key rows: {{dupes[:5]}}"

                @pytest.mark.parametrize("column", _NULLABLE_COLUMNS)
                def test_nullable_columns_allow_null(self, db_connection, column):
                    """Columns flagged nullable in DataHub should accept NULL."""
                    result = validate_nullable(db_connection, "{schema.name}", column, expected_nullable=True)
                    assert result.ok, result.message

                @pytest.mark.parametrize("column", _NON_NULLABLE_COLUMNS)
                def test_non_nullable_columns_reject_null(self, db_connection, column):
                    """Columns flagged NOT NULL in DataHub should reject NULL."""
                    result = validate_nullable(db_connection, "{schema.name}", column, expected_nullable=False)
                    assert result.ok, result.message
            ''')
        return code

    # ------------------------------------------------------------------ lineage tests

    def generate_lineage_tests(self, dataset_urn: str, direction: str = "UPSTREAM") -> TestArtifact:
        """Generate a pytest module that validates lineage continuity."""
        edges = self.inspector.get_lineage(dataset_urn, direction=direction)
        return TestArtifact(
            test_name=f"test_lineage_{self._slug(dataset_urn.split(':')[-1])[:60]}",
            test_code=self._render_lineage_test(dataset_urn, edges, direction),
            dataset_urn=dataset_urn,
            description="Lineage continuity test — verify upstream/downstream datasets map correctly.",
            soc2_controls=["CC6.1"],
        )

    def _render_lineage_test(self, dataset_urn: str, edges: list[LineageEdge], direction: str) -> str:
        edge_reps = [
            {
                "source": e.source_dataset or e.source_urn,
                "target": e.target_dataset or e.target_urn,
                "column_mappings": e.column_mappings,
            }
            for e in edges
        ]
        code = dedent(f'''\
            """Lineage continuity test for {dataset_urn}.

            Auto-generated by Tenant Shield from DataHub lineage metadata.
            Direction: {direction}.
            """
            import pytest

            from tests.helpers.lineage_validator import verify_lineage_edge


            DATASET_URN = "{dataset_urn}"
            EXPECTED_EDGES = {edge_reps!r}


            @pytest.mark.integration
            @pytest.mark.lineage
            class Test{self._pascal(dataset_urn)}Lineage:
                """Each upstream/downstream edge declared in DataHub must be live."""

                @pytest.mark.parametrize("edge", EXPECTED_EDGES)
                def test_lineage_edge_active(self, db_connection, edge):
                    """Edge declared in DataHub should be live (source → target)."""
                    ok = verify_lineage_edge(db_connection, edge["source"], edge["target"], edge["column_mappings"])
                    assert ok, f"Broken lineage: {{edge['source']}} → {{edge['target']}}"

                def test_expected_edge_count(self, db_connection):
                    """The number of live edges must match DataHub metadata."""
                    live_edges = [e for e in EXPECTED_EDGES if verify_lineage_edge(db_connection, e["source"], e["target"], e["column_mappings"])]
                    assert len(live_edges) == len(EXPECTED_EDGES), f"Missing {{len(EXPECTED_EDGES) - len(live_edges)}} lineage edges"
            ''')
        return code

    # ------------------------------------------------------------------ ownership/observability tests

    def generate_ownership_tests(self, dataset_urn: str) -> TestArtifact:
        """Generated test: ensure every dataset has a declared owner in DataHub."""
        schema = self.inspector.get_dataset_schema(dataset_urn)
        has_owner = bool(schema.owner)
        return TestArtifact(
            test_name=f"test_owner_{self._slug(schema.name)}",
            test_code=dedent(f'''\
                """Ownership test for {schema.name} (auto-generated).

                SOC 2 control: CC6.1 — accountability for data stewardship.
                """
                import pytest

                @pytest.mark.security
                def test_dataset_has_owner():
                    """Dataset must have a declared owner in DataHub."""
                    assert {has_owner!r}, "Dataset {{0!r}} has no declared owner".format("{schema.name}")
                '''),
            dataset_urn=dataset_urn,
            description="Ownership completeness test — every dataset must have a DataHub owner.",
            soc2_controls=["CC6.1"],
        )

    # ------------------------------------------------------------------ batch generation

    def generate_full_suite(self, dataset_urns: Iterable[str]) -> list[TestArtifact]:
        """Generate a complete test suite covering multiple datasets."""
        artifacts: list[TestArtifact] = []
        for urn in dataset_urns:
            try:
                artifacts.append(self.generate_schema_tests(urn))
                artifacts.append(self.generate_lineage_tests(urn))
                artifacts.append(self.generate_ownership_tests(urn))
            except Exception as exc:
                logger.warning("gen.failed", extra={"extra_data": {"urn": urn, "error": str(exc)}})
        return artifacts

    # ------------------------------------------------------------------ helpers

    @staticmethod
    def _slug(name: str) -> str:
        return (
            name.lower()
            .replace(":", "_")
            .replace(".", "_")
            .replace("(", "")
            .replace(")", "")
            .replace(",", "_")
            .replace("-", "_")
            .replace(" ", "_")
        )

    @staticmethod
    def _pascal(name: str) -> str:
        cleaned = TestGenerator._slug(name)
        return "".join(p.capitalize() for p in cleaned.split("_") if p) or "Dataset"
