"""Metadata-aware Data Contract and Probe Test Generator.

Translates DataHub / dbt catalog schemas, column nullability, PK constraints,
and upstream/downstream lineage into executable pytest test suites mapped
to SOC 2 controls (CC6.1 Data Integrity, CC7.2 System Monitoring).
"""

from datetime import datetime, timezone
import re
from textwrap import dedent
from typing import List, Optional
import uuid

from app.models.asset import AssetNode
from app.models.contract import (
    ColumnConstraint,
    ContractExecutionResult,
    ContractSpec,
    GeneratedContractTest,
)


class ContractTestGenerator:
    """Generates and executes metadata-aware pytest data contracts."""

    @staticmethod
    def _slug(name: str) -> str:
        return re.sub(r"[^a-zA-Z0-9_]", "_", name).lower()

    @staticmethod
    def _pascal(name: str) -> str:
        return "".join(part.capitalize() for part in re.split(r"[^a-zA-Z0-9]", name) if part)

    def extract_contract_from_node(self, node: AssetNode) -> ContractSpec:
        """Derive a ContractSpec from an AssetNode."""
        columns: List[ColumnConstraint] = []
        for field in node.schema_fields:
            # Common schema string formats: "id:INTEGER", "id (INT)", "id"
            if ":" in field:
                col_name, col_type = field.split(":", 1)
            elif " " in field:
                col_name, col_type = field.split(" ", 1)
            else:
                col_name, col_type = field, "VARCHAR"

            col_name = col_name.strip()
            col_type = col_type.strip().strip("()")
            is_pk = col_name.lower() in ("id", "pk", f"{self._slug(node.name)}_id")
            nullable = not is_pk and not col_name.lower().endswith("_id")

            columns.append(
                ColumnConstraint(
                    name=col_name,
                    data_type=col_type,
                    nullable=nullable,
                    is_primary_key=is_pk,
                )
            )

        return ContractSpec(
            dataset_urn=str(node.urn),
            dataset_name=node.name,
            owner=node.owner,
            columns=columns,
            upstream_lineage=[str(u) for u in node.upstream],
            criticality=node.criticality,
            soc2_controls=["CC6.1", "CC7.2"],
        )

    def generate_pytest_suite(self, contract: ContractSpec) -> GeneratedContractTest:
        """Generate a complete, executable pytest suite from a ContractSpec."""
        test_id = f"contract_test_{uuid.uuid4().hex[:8]}"
        pascal_name = self._pascal(contract.dataset_name)
        now_str = datetime.now(timezone.utc).isoformat()

        expected_columns = [(c.name, c.data_type, c.nullable) for c in contract.columns]
        pk_columns = [c.name for c in contract.columns if c.is_primary_key]
        non_null_cols = [c.name for c in contract.columns if not c.nullable]
        nullable_cols = [c.name for c in contract.columns if c.nullable]

        code = dedent(f'''\
            """Auto-Generated Data Contract Test Suite for {contract.dataset_name}.

            Generated by Cortex Autopilot at {now_str}.
            Dataset URN : {contract.dataset_urn}
            Owner       : {contract.owner or "UNASSIGNED"}
            Criticality : {contract.criticality.upper()}
            SOC 2 Controls: CC6.1 (Data Integrity), CC7.2 (System Monitoring)
            """
            import pytest


            DATASET_URN = "{contract.dataset_urn}"
            DATASET_NAME = "{contract.dataset_name}"
            OWNER = "{contract.owner or ''}"
            CRITICALITY = "{contract.criticality}"
            EXPECTED_COLUMNS = {expected_columns!r}
            PRIMARY_KEYS = {pk_columns!r}
            NON_NULL_COLUMNS = {non_null_cols!r}
            NULLABLE_COLUMNS = {nullable_cols!r}
            UPSTREAM_DEPENDENCIES = {contract.upstream_lineage!r}


            @pytest.mark.data_contract
            @pytest.mark.soc2_cc6_1
            class Test{pascal_name}SchemaContract:
                """Validate schema integrity and constraints declared in DataHub."""

                def test_expected_columns_present(self, live_schema):
                    """Ensure all catalog columns exist in the target dataset."""
                    expected_names = {{col[0] for col in EXPECTED_COLUMNS}}
                    live_names = set(live_schema.get_column_names(DATASET_NAME))
                    missing = expected_names - live_names
                    assert not missing, f"Schema drift detected! Missing columns: {{missing}}"

                def test_primary_key_uniqueness(self, live_dataset):
                    """Verify primary key columns satisfy uniqueness constraints."""
                    if not PRIMARY_KEYS:
                        pytest.skip("No primary key declared in metadata catalog.")
                    duplicates = live_dataset.find_duplicate_keys(DATASET_NAME, PRIMARY_KEYS)
                    assert not duplicates, f"Primary key violation on {{PRIMARY_KEYS}}: {{duplicates[:5]}}"

                @pytest.mark.parametrize("col_name", NON_NULL_COLUMNS)
                def test_not_null_constraints(self, live_dataset, col_name):
                    """Enforce non-nullability on required contract columns."""
                    null_count = live_dataset.count_nulls(DATASET_NAME, col_name)
                    assert null_count == 0, f"Column '{{col_name}}' has {{null_count}} NULL violations!"


            @pytest.mark.data_contract
            @pytest.mark.soc2_cc7_2
            class Test{pascal_name}GovernanceAndLineage:
                """Validate ownership completeness and lineage continuity."""

                def test_ownership_governance(self):
                    """SOC 2 CC6.1: High/Critical datasets must have a declared owner."""
                    if CRITICALITY in ("high", "critical"):
                        assert OWNER and OWNER.lower() != "unassigned", (
                            f"Governance violation: Critical dataset '{{DATASET_NAME}}' has no owner!"
                        )

                def test_upstream_lineage_continuity(self, catalog_client):
                    """Ensure all upstream dependencies exist and are healthy."""
                    for upstream_urn in UPSTREAM_DEPENDENCIES:
                        upstream_node = catalog_client.get_asset(upstream_urn)
                        assert upstream_node is not None, (
                            f"Lineage broken! Upstream dataset '{{upstream_urn}}' is missing."
                        )
            ''')

        integrity_score = 100.0
        if not contract.owner and contract.criticality in ("high", "critical"):
            integrity_score -= 20.0
        if not pk_columns:
            integrity_score -= 10.0

        return GeneratedContractTest(
            test_id=test_id,
            dataset_urn=contract.dataset_urn,
            dataset_name=contract.dataset_name,
            test_code=code,
            test_type="full_suite",
            soc2_controls=["CC6.1", "CC7.2"],
            integrity_score=max(0.0, integrity_score),
        )

    def evaluate_contract_mock(self, contract: ContractSpec) -> ContractExecutionResult:
        """Simulate execution of contract tests against the contract definition."""
        findings = []
        passed = 0
        failed = 0
        skipped = 0

        # Test 1: Schema columns
        if contract.columns:
            passed += 1
            findings.append({"test": "test_expected_columns_present", "status": "PASSED", "detail": f"All {len(contract.columns)} columns verified."})
        else:
            failed += 1
            findings.append({"test": "test_expected_columns_present", "status": "FAILED", "detail": "Dataset has empty schema definition."})

        # Test 2: Primary key
        pk_cols = [c.name for c in contract.columns if c.is_primary_key]
        if pk_cols:
            passed += 1
            findings.append({"test": "test_primary_key_uniqueness", "status": "PASSED", "detail": f"PK unique on {pk_cols}."})
        else:
            skipped += 1
            findings.append({"test": "test_primary_key_uniqueness", "status": "SKIPPED", "detail": "No primary key declared in catalog."})

        # Test 3: Not-null checks
        non_null_cols = [c.name for c in contract.columns if not c.nullable]
        for col in non_null_cols:
            passed += 1
            findings.append({"test": f"test_not_null[{col}]", "status": "PASSED", "detail": f"Column {col} NOT NULL constraint satisfied."})

        # Test 4: Ownership
        if contract.criticality in ("high", "critical") and not contract.owner:
            failed += 1
            findings.append({"test": "test_ownership_governance", "status": "FAILED", "detail": f"Critical dataset {contract.dataset_name} has no designated owner (SOC 2 violation)."})
        else:
            passed += 1
            findings.append({"test": "test_ownership_governance", "status": "PASSED", "detail": f"Owner {contract.owner or 'assigned'} compliant with SOC 2 CC6.1."})

        # Test 5: Lineage
        passed += 1
        findings.append({"test": "test_upstream_lineage_continuity", "status": "PASSED", "detail": f"{len(contract.upstream_lineage)} upstream links validated."})

        total = passed + failed + skipped
        status = "passed" if failed == 0 else "failed"

        return ContractExecutionResult(
            dataset_urn=contract.dataset_urn,
            total_tests=total,
            passed_tests=passed,
            failed_tests=failed,
            skipped_tests=skipped,
            duration_seconds=0.042,
            status=status,
            findings=findings,
            soc2_compliance_met=(failed == 0),
        )


contract_test_generator = ContractTestGenerator()
