"""Lineage continuity test for urn:li:dataset:(urn:li:dataPlatform:postgres,public.projects,PROD).

Auto-generated by Tenant Shield from DataHub lineage metadata.
Direction: UPSTREAM.
"""
import pytest

from tests.helpers.lineage_validator import verify_lineage_edge


DATASET_URN = "urn:li:dataset:(urn:li:dataPlatform:postgres,public.projects,PROD)"
EXPECTED_EDGES = [{'source': 'public.users', 'target': 'public.projects', 'column_mappings': [{'source': 'tenant_id', 'target': 'tenant_id'}]}]


@pytest.mark.integration
@pytest.mark.lineage
class TestUrnLiDatasetUrnLiDataplatformPostgresPublicProjectsProdLineage:
    """Each upstream/downstream edge declared in DataHub must be live."""

    @pytest.mark.parametrize("edge", EXPECTED_EDGES)
    def test_lineage_edge_active(self, db_connection, edge):
        """Edge declared in DataHub should be live (source → target)."""
        ok = verify_lineage_edge(db_connection, edge["source"], edge["target"], edge["column_mappings"])
        assert ok, f"Broken lineage: {edge['source']} → {edge['target']}"

    def test_expected_edge_count(self, db_connection):
        """The number of live edges must match DataHub metadata."""
        live_edges = [e for e in EXPECTED_EDGES if verify_lineage_edge(db_connection, e["source"], e["target"], e["column_mappings"])]
        assert len(live_edges) == len(EXPECTED_EDGES), f"Missing {len(EXPECTED_EDGES) - len(live_edges)} lineage edges"
