"""Schema integrity test for public.users on postgres.

Auto-generated by Tenant Shield from DataHub metadata at 2026-08-06T07:46:47.184523+00:00.
Owner: data-team@workflowpro.com
Schema integrity score: 1.0

SOC 2 controls: CC6.1 (data integrity), CC7.2 (system monitoring).
"""
import pytest

from tests.helpers.schema_validator import validate_schema, validate_nullable, validate_primary_key


DATASET_URN = "urn:li:dataset:(urn:li:dataPlatform:postgres,public.users,PROD)"
EXPECTED_COLUMNS = [('created_at', 'TIMESTAMP', 'NOT NULL'), ('email', 'STRING', 'NOT NULL'), ('id', 'INT', 'NOT NULL'), ('last_login', 'TIMESTAMP', 'NULL'), ('role', 'STRING', 'NOT NULL'), ('tenant_id', 'STRING', 'NOT NULL')]
PRIMARY_KEY_COLUMNS = ['id']
_NULLABLE_COLUMNS = ['last_login']
_NON_NULLABLE_COLUMNS = ['id', 'email', 'tenant_id', 'role', 'created_at']


@pytest.mark.security
@pytest.mark.schema
class TestPublicUsersSchema:
    """Validate the public.users schema against DataHub source-of-truth."""

    def test_expected_columns_present(self, db_connection):
        """Ensure every expected column appears in the live table."""
        missing = validate_schema(db_connection, "public.users", EXPECTED_COLUMNS)
        assert not missing, f"Missing columns: {missing}"

    def test_primary_key_unique(self, db_connection):
        """Primary key columns MUST be unique and non-null."""
        if not PRIMARY_KEY_COLUMNS:
            pytest.skip("No primary key declared in DataHub")
        dupes = validate_primary_key(db_connection, "public.users", PRIMARY_KEY_COLUMNS)
        assert not dupes, f"Duplicate primary key rows: {dupes[:5]}"

    @pytest.mark.parametrize("column", _NULLABLE_COLUMNS)
    def test_nullable_columns_allow_null(self, db_connection, column):
        """Columns flagged nullable in DataHub should accept NULL."""
        result = validate_nullable(db_connection, "public.users", column, expected_nullable=True)
        assert result.ok, result.message

    @pytest.mark.parametrize("column", _NON_NULLABLE_COLUMNS)
    def test_non_nullable_columns_reject_null(self, db_connection, column):
        """Columns flagged NOT NULL in DataHub should reject NULL."""
        result = validate_nullable(db_connection, "public.users", column, expected_nullable=False)
        assert result.ok, result.message
